#! /bin/sh


bspc monitor -d 1 2 3 4 5

bspc config border_width          2
bspc config borderless_monocle    false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true

bspc rule -a Zathura state=tiled

# autostart
picom --experimental-backends &
feh --bg-fill ~/pictures/wall/iceland.png &
xrdb merge ~/.Xresources &
pgrep bspswallow || bspswallow &
pgrep cleanfullscreen || cleanfullscreen &
pgrep nobordersfloating || nobordersfloating &
~/.config/polybar/launch.sh &
sxhkd
